CREATE TABLE users(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	hourly_rate DECIMAL(9,2)
);

CREATE TABLE bugs(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	title TEXT NOT NULL,
	description TEXT NOT NULL
);

CREATE TABLE hourLog(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER,
	bug_id INTEGER,
	hours DECIMAL(5,2),
	FOREIGN KEY (user_id) REFERENCES users(id),
	FOREIGN KEY (bug_id) REFERENCES bugs(id)
);
